package backward;

import com.ftn.sbnz.model.models.Woman
import com.ftn.sbnz.model.models.Man
import com.ftn.sbnz.model.models.Parent

query isWoman (String name)
    Woman(name;)
end

query isMan (String name)
    Man(name;)
end

query isParent (String parentName, String childName)
    Parent(parentName, childName;)
end

rule "is a woman"
    when
        String(this == "woman")
        isWoman(name;)
    then
        System.out.println(name);
end

rule "is a man"
    when
        String(this == "man")
        isMan(name;)
    then
        System.out.println(name);
end

rule "is a parent"
    when
        String(this == "parent")
        isParent(parentName, childName;)
    then
        System.out.println(parentName + " is a parent of " + childName);
end


