package backward;

import com.ftn.sbnz.model.models.backwardModel.BackwardModel;
import com.ftn.sbnz.model.models.backwardModel.BackwardType;

global String ingredientGlobal;


query pronadji(String sastojak, String lek)
    BackwardModel(sastojak, lek; )
    or
    (BackwardModel(z, lek; ) and pronadji(sastojak, z; ))
end

rule "go4"
when
    $model: BackwardModel($ingredient: ingredient != ingredientGlobal, $medicine:medicine, backwardType == BackwardType.MEDICINE)
    not BackwardModel(ingredient == ingredientGlobal, medicine == $medicine)
    pronadji($ingredient, $medicine; )
then
    System.out.println($medicine);
end

